[package]
name = "terrane-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true


[dependencies]
indoc = "2"
num-bigint = "0.4"
num-traits = "0.2"
prettyplease = "0.2"
proc-macro2 = "1"
quote = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
syn = { version = "2", features = ["extra-traits", "fold", "full"] }
toml = "0.8"
[lints]
workspace = true
