[workspace]
members = [
    "crates/terrane-cli",
    "crates/terrane-compiler",
    "crates/terrane-int-support",
    "crates/terrane-collection-support",
    "crates/terrane-scalar-support",
    "crates/terrane-language-server",
    "crates/terrane-string-support",
    "crates/terrane-stream-abi",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"
rust-version = "1.85"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
