use super::prelude::*;
pub(super) const BUILTIN_ERROR_NAMES: &[&str] = &[
    "arithmetic-overflow",
    "division-by-zero",
    "integer-conversion-overflow",
    "negative-shift-count",
    "coercion-error",
    "decode-error",
    "index-error",
    "missing-key",
    "dependency-error",
    "dependency-panic",
];

#[expect(
    clippy::too_many_lines,
    reason = "compiler-owned namespace registration is a single auditable inventory"
)]
pub(super) fn bootstrap_namespaces() -> BTreeMap<String, Namespace> {
    let mut namespaces = BTreeMap::new();
    namespaces.insert(
        "/core/output".to_owned(),
        namespace_with_objects("/core/output", ["print"], SymbolKind::Function),
    );
    namespaces.insert(
        "/core/async".to_owned(),
        namespace_with_objects("/core/async", ["task-scope"], SymbolKind::Function),
    );
    add_private_host_bindings(
        &mut namespaces,
        "/core/codecs",
        "capabilities",
        [
            "hex-encode",
            "hex-decode",
            "base64-encode",
            "base64-decode",
            "result-failed",
            "result-message",
            "result-bytes",
        ],
    );
    add_private_host_bindings(
        &mut namespaces,
        "/core/compression",
        "capabilities",
        [
            "compress",
            "decompress",
            "result-failed",
            "result-resource-limit",
            "result-message",
            "result-bytes",
        ],
    );
    add_private_host_bindings(
        &mut namespaces,
        "/core/concurrency",
        "concurrency",
        [
            "platform-capability",
            "platform-result",
            "no-capability",
            "int-mutex",
            "int-mutex-load",
            "int-mutex-store",
            "int-mutex-add",
            "int-read-write-lock",
            "int-read-write-lock-read",
            "int-read-write-lock-write",
            "atomic-int64",
            "atomic-int64-load",
            "atomic-int64-store",
            "atomic-int64-add",
            "thread-local-int",
            "thread-local-int-get",
            "thread-local-int-set",
            "result-failed",
            "result-message",
            "result-int",
            "result-bool",
        ],
    );
    add_private_host_bindings(
        &mut namespaces,
        "/core/concurrency",
        "capabilities",
        [
            "cancellation-token",
            "cancel",
            "result-deadline-exceeded",
            "result-capability",
        ],
    );
    if let Some(concurrency) = namespaces.get_mut("/core/concurrency") {
        concurrency.symbols.insert(
            "channel".to_owned(),
            compiler_owned_object("/core/concurrency", "channel", SymbolKind::Function),
        );
        for name in ["mutex", "read-write-lock", "shared-cell"] {
            concurrency.symbols.insert(
                name.to_owned(),
                compiler_owned_object("/core/concurrency", name, SymbolKind::Function),
            );
        }
        for policy in [
            "channel-block",
            "channel-fail-send",
            "channel-drop-newest",
            "channel-drop-oldest",
        ] {
            let mut symbol =
                compiler_owned_object("/core/concurrency", policy, SymbolKind::Binding);
            symbol.constant = true;
            concurrency.symbols.insert(policy.to_owned(), symbol);
        }
    }
    add_private_host_bindings(
        &mut namespaces,
        "/core/documents",
        "data",
        [
            "platform-data-result",
            "make-document-none",
            "make-document-bool",
            "make-document-string",
            "make-document-integer",
            "make-document-decimal",
            "make-document-list",
            "document-list-append",
            "make-document-map",
            "document-map-insert",
            "empty-document",
            "data-failed",
            "data-message",
            "data-path",
            "data-expected",
            "data-encoded",
            "document-kind",
            "document-text",
            "document-coefficient",
            "document-exponent",
            "document-length",
            "document-item",
            "document-key",
            "document-field",
            "validate-mapping",
        ],
    );
    add_private_host_bindings(
        &mut namespaces,
        "/core/filesystem",
        "system",
        [
            "filesystem-exists",
            "filesystem-metadata",
            "filesystem-realpath",
            "filesystem-read-link",
            "filesystem-read-bounded",
            "filesystem-write-atomic",
            "filesystem-rename",
            "filesystem-remove",
            "result-failed",
            "result-message",
            "result-text",
            "result-detail",
            "result-bytes",
            "result-int",
            "result-bool",
            "filesystem-authority",
            "acquire-filesystem-authority",
        ],
    );
    add_private_host_bindings(
        &mut namespaces,
        "/core/filesystem",
        "streams",
        [
            "resource-handle",
            "open-file",
            "open-directory-beneath",
            "open-file-beneath",
            "read",
            "write",
            "flush",
            "sync-data",
            "sync-all",
            "close",
            "release",
        ],
    );
    add_private_host_bindings(
        &mut namespaces,
        "/core/documents/json",
        "data",
        ["json-parse", "json-canonical"],
    );
    if let Some(json) = namespaces.get_mut("/core/documents/json") {
        json.symbols.insert(
            "decode-typed-json".to_owned(),
            compiler_owned_object(
                "/core/documents/json",
                "decode-typed-json",
                SymbolKind::Function,
            ),
        );
    }
    add_private_host_bindings(
        &mut namespaces,
        "/core/networking",
        "capabilities",
        [
            "platform-resource-handle",
            "platform-capability",
            "platform-result",
            "no-resource",
            "failed-result",
            "parse-ip",
            "parse-host-name",
            "parse-socket",
            "parse-socket-text",
            "tcp-bind",
            "tcp-connect",
            "tcp-connect-host",
            "tcp-accept",
            "tcp-read",
            "tcp-write",
            "tcp-shutdown",
            "tcp-configure",
            "udp-bind",
            "udp-send-to",
            "udp-receive-from",
            "udp-configure",
            "cancellation-token",
            "cancel",
            "dns-lookup",
            "tcp-connect-async",
            "tcp-connect-host-async",
            "tcp-accept-async",
            "tcp-read-async",
            "tcp-write-async",
            "udp-send-to-async",
            "udp-receive-from-async",
            "dns-lookup-async",
            "close",
            "result-failed",
            "result-truncated",
            "result-deadline-exceeded",
            "result-message",
            "result-text",
            "result-detail",
            "result-bytes",
            "result-int",
            "result-bool",
            "result-entries",
            "result-resource",
        ],
    );
    add_private_host_bindings(
        &mut namespaces,
        "/core/process",
        "system",
        [
            "process-arguments",
            "environment-entries",
            "process-exit",
            "platform-value-is-text",
            "platform-value-text",
            "platform-value-bytes",
        ],
    );
    add_private_host_bindings(
        &mut namespaces,
        "/core/process",
        "adapters",
        [
            "platform-result",
            "system-host-name",
            "result-failed",
            "result-message",
            "result-text",
            "result-bool",
        ],
    );
    add_private_host_bindings(
        &mut namespaces,
        "/core/random",
        "capabilities",
        [
            "platform-capability",
            "secure-random",
            "pseudo-random",
            "random-bytes",
            "random-bounded",
            "random-split",
            "secret-buffer",
            "destroy-secret",
            "digest",
            "hmac",
            "constant-time-equal",
            "result-failed",
            "result-message",
            "result-bytes",
            "result-int",
            "result-capability",
        ],
    );
    add_private_host_bindings(
        &mut namespaces,
        "/core/streams",
        "streams",
        [
            "resource-handle",
            "acquire-stdin",
            "acquire-stdout",
            "acquire-stderr",
            "read",
            "read-async",
            "write",
            "flush",
            "sync-data",
            "sync-all",
            "close",
            "release",
        ],
    );
    add_private_host_bindings(
        &mut namespaces,
        "/core/networking/tls",
        "capabilities",
        [
            "platform-resource-handle",
            "no-resource",
            "tls-client",
            "tls-read",
            "tls-write",
            "tls-shutdown",
            "tls-client-async",
            "tls-read-async",
            "tls-write-async",
            "tls-shutdown-async",
            "close",
            "result-failed",
            "result-deadline-exceeded",
            "result-message",
            "result-text",
            "result-bytes",
            "result-int",
            "result-bool",
            "result-resource",
        ],
    );
    add_private_host_bindings(
        &mut namespaces,
        "/core/urls",
        "data",
        [
            "platform-url-result",
            "url-parse",
            "url-failed",
            "url-message",
            "url-serialized",
            "url-display",
            "url-scheme",
            "url-username",
            "url-password",
            "url-host",
            "url-port",
            "url-path",
            "url-fragment",
            "url-origin",
            "url-query-length",
            "url-query-key",
            "url-query-value",
        ],
    );
    add_private_host_bindings(
        &mut namespaces,
        "/core/random/uuid",
        "capabilities",
        [
            "platform-capability",
            "uuid-parse",
            "uuid-v4",
            "uuid-v7",
            "result-failed",
            "result-message",
            "result-text",
            "result-bytes",
        ],
    );
    add_private_host_bindings(
        &mut namespaces,
        "/core/documents/yaml",
        "data",
        ["yaml-parse", "json-canonical"],
    );
    if let Some(yaml) = namespaces.get_mut("/core/documents/yaml") {
        yaml.symbols.insert(
            "decode-typed-yaml".to_owned(),
            compiler_owned_object(
                "/core/documents/yaml",
                "decode-typed-yaml",
                SymbolKind::Function,
            ),
        );
    }
    namespaces.insert("/core/logging".to_owned(), Namespace::default());
    add_private_host_bindings(
        &mut namespaces,
        "/core/logging",
        "logging",
        [
            "log-empty-fields",
            "log-empty-spans",
            "log-memory-sink",
            "log-console-sink",
            "log-failing-sink",
            "log-no-sink",
            "log-write",
            "log-drain",
            "log-discarded-count",
            "log-drain-fallback",
            "log-install-dependency-bridge",
            "log-result-failed",
            "log-result-message",
            "log-result-entries",
            "log-result-capability",
        ],
    );
    let mut types = vec![
        "int".to_owned(),
        "float".to_owned(),
        "bool".to_owned(),
        "string".to_owned(),
        "bytes".to_owned(),
        "encoding".to_owned(),
        "none".to_owned(),
        "float32".to_owned(),
        "float64".to_owned(),
        "overflow-result".to_owned(),
        "div-rem-result".to_owned(),
    ];
    types.extend(
        TypeCategory::ABSTRACT_SOURCE_NAMES
            .into_iter()
            .map(|(name, _)| name.to_owned()),
    );
    for prefix in ["int", "uint"] {
        for width in [8, 16, 32, 64, 128] {
            types.push(format!("{prefix}{width}"));
        }
    }
    namespaces.insert(
        "/core/types".to_owned(),
        namespace_with_objects(
            "/core/types",
            types.iter().map(std::string::String::as_str),
            SymbolKind::TypeDescriptor,
        ),
    );
    namespaces.insert(
        "/core/encodings".to_owned(),
        namespace_with_objects(
            "/core/encodings",
            ["utf8", "utf16-le", "utf16-be", "utf32-le", "utf32-be"],
            SymbolKind::TypeDescriptor,
        ),
    );
    let mut errors = namespace_with_objects(
        "/core/errors",
        BUILTIN_ERROR_NAMES.iter().copied(),
        SymbolKind::ErrorObject,
    );
    errors.symbols.insert(
        "throwable".to_owned(),
        compiler_owned_object("/core/errors", "throwable", SymbolKind::Interface),
    );
    namespaces.insert("/core/errors".to_owned(), errors);
    namespaces.insert(
        "/core/collections".to_owned(),
        namespace_with_objects(
            "/core/collections",
            [
                "iterator",
                "iteration-step",
                "list",
                "map",
                "set",
                "tuple",
                "range",
                "entry",
                "unordered-map",
                "unordered-set",
            ],
            SymbolKind::TypeDescriptor,
        ),
    );
    namespaces
}
