fn terrane_platform_parse_ip(text: String) -> TerranePlatformResult { terrane_platform_support::parse_ip(&text) }
fn terrane_platform_parse_socket(ip: &String, port: &terrane_int_support::Int) -> TerranePlatformResult { terrane_platform_support::parse_socket(ip, port.as_big().to_string().parse::<i128>().unwrap_or(-1)) }
fn terrane_platform_tcp_bind(address: String) -> TerranePlatformResult { terrane_platform_support::tcp_bind(&address) }
fn terrane_platform_tcp_connect(address: String, deadline: terrane_int_support::Int, cancelled: bool) -> TerranePlatformResult { terrane_platform_support::tcp_connect(&address, deadline.as_big().to_string().parse::<i128>().unwrap_or(-1), cancelled) }
fn terrane_platform_tcp_accept(listener: &TerranePlatformCapability, deadline: terrane_int_support::Int, cancelled: bool) -> TerranePlatformResult { terrane_platform_support::tcp_accept(listener, deadline.as_big().to_string().parse::<i128>().unwrap_or(-1), cancelled) }
fn terrane_platform_tcp_read(stream: &TerranePlatformCapability, limit: terrane_int_support::Int, deadline: terrane_int_support::Int, cancelled: bool) -> TerranePlatformResult { terrane_platform_support::tcp_read(stream, limit.as_big().to_string().parse::<i128>().unwrap_or(-1), deadline.as_big().to_string().parse::<i128>().unwrap_or(-1), cancelled) }
fn terrane_platform_tcp_write(stream: &TerranePlatformCapability, data: Vec<u8>, deadline: terrane_int_support::Int, cancelled: bool) -> TerranePlatformResult { terrane_platform_support::tcp_write(stream, &data, deadline.as_big().to_string().parse::<i128>().unwrap_or(-1), cancelled) }
fn terrane_platform_tcp_shutdown(stream: &TerranePlatformCapability, direction: String) -> TerranePlatformResult { terrane_platform_support::tcp_shutdown(stream, &direction) }
fn terrane_platform_udp_bind(address: String) -> TerranePlatformResult { terrane_platform_support::udp_bind(&address) }
fn terrane_platform_udp_send_to(socket: &TerranePlatformCapability, data: Vec<u8>, address: String, deadline: terrane_int_support::Int, cancelled: bool) -> TerranePlatformResult { terrane_platform_support::udp_send_to(socket, &data, &address, deadline.as_big().to_string().parse::<i128>().unwrap_or(-1), cancelled) }
fn terrane_platform_udp_receive_from(socket: &TerranePlatformCapability, limit: terrane_int_support::Int, deadline: terrane_int_support::Int, cancelled: bool) -> TerranePlatformResult { terrane_platform_support::udp_receive_from(socket, limit.as_big().to_string().parse::<i128>().unwrap_or(-1), deadline.as_big().to_string().parse::<i128>().unwrap_or(-1), cancelled) }
fn terrane_platform_dns_lookup(host: String, port: terrane_int_support::Int, deadline: terrane_int_support::Int, cancelled: bool) -> TerranePlatformResult { terrane_platform_support::dns_lookup(&host, port.as_big().to_string().parse::<i128>().unwrap_or(-1), deadline.as_big().to_string().parse::<i128>().unwrap_or(-1), cancelled) }
fn terrane_platform_close(capability: &TerranePlatformCapability) -> TerranePlatformResult { terrane_platform_support::close(capability) }
