fn terrane_platform_parse_ip(text: String) -> TerranePlatformResult { terrane_platform_support::parse_ip(&text) }
fn terrane_platform_parse_host_name(text: String) -> TerranePlatformResult { terrane_platform_support::parse_host_name(&text) }
fn terrane_platform_parse_socket(ip: &String, port: &terrane_int_support::Int) -> TerranePlatformResult { terrane_platform_support::parse_socket(ip, terrane_platform_i128!(port, "socket port")) }
fn terrane_platform_tcp_bind(address: String) -> TerranePlatformResult { terrane_platform_support::tcp_bind(&address) }
fn terrane_platform_tcp_connect(address: String, deadline: terrane_int_support::Int, cancellation: &TerranePlatformCapability) -> TerranePlatformResult { terrane_platform_support::tcp_connect(&address, terrane_platform_i128!(deadline, "TCP connect deadline"), cancellation) }
fn terrane_platform_tcp_connect_host(host: String, port: terrane_int_support::Int, deadline: terrane_int_support::Int, cancellation: &TerranePlatformCapability) -> TerranePlatformResult { terrane_platform_support::tcp_connect_host(&host, terrane_platform_i128!(port, "TCP host port"), terrane_platform_i128!(deadline, "TCP host connect deadline"), cancellation) }
fn terrane_platform_tcp_accept(listener: &TerranePlatformCapability, deadline: terrane_int_support::Int, cancellation: &TerranePlatformCapability) -> TerranePlatformResult { terrane_platform_support::tcp_accept(listener, terrane_platform_i128!(deadline, "TCP accept deadline"), cancellation) }
fn terrane_platform_tcp_read(stream: &TerranePlatformCapability, limit: terrane_int_support::Int, deadline: terrane_int_support::Int, cancellation: &TerranePlatformCapability) -> TerranePlatformResult { terrane_platform_support::tcp_read(stream, terrane_platform_i128!(limit, "TCP read limit"), terrane_platform_i128!(deadline, "TCP read deadline"), cancellation) }
fn terrane_platform_tcp_write(stream: &TerranePlatformCapability, data: Vec<u8>, deadline: terrane_int_support::Int, cancellation: &TerranePlatformCapability) -> TerranePlatformResult { terrane_platform_support::tcp_write(stream, &data, terrane_platform_i128!(deadline, "TCP write deadline"), cancellation) }
fn terrane_platform_tcp_shutdown(stream: &TerranePlatformCapability, direction: String) -> TerranePlatformResult { terrane_platform_support::tcp_shutdown(stream, &direction) }
fn terrane_platform_tcp_configure(stream: &TerranePlatformCapability, no_delay: bool, ttl: terrane_int_support::Int) -> TerranePlatformResult { terrane_platform_support::tcp_configure(stream, no_delay, terrane_platform_i128!(ttl, "TCP TTL")) }
fn terrane_platform_udp_bind(address: String) -> TerranePlatformResult { terrane_platform_support::udp_bind(&address) }
fn terrane_platform_udp_configure(socket: &TerranePlatformCapability, broadcast: bool, ttl: terrane_int_support::Int) -> TerranePlatformResult { terrane_platform_support::udp_configure(socket, broadcast, terrane_platform_i128!(ttl, "UDP TTL")) }
fn terrane_platform_udp_send_to(socket: &TerranePlatformCapability, data: Vec<u8>, address: String, deadline: terrane_int_support::Int, cancellation: &TerranePlatformCapability) -> TerranePlatformResult { terrane_platform_support::udp_send_to(socket, &data, &address, terrane_platform_i128!(deadline, "UDP send deadline"), cancellation) }
fn terrane_platform_udp_receive_from(socket: &TerranePlatformCapability, limit: terrane_int_support::Int, deadline: terrane_int_support::Int, cancellation: &TerranePlatformCapability) -> TerranePlatformResult { terrane_platform_support::udp_receive_from(socket, terrane_platform_i128!(limit, "UDP receive limit"), terrane_platform_i128!(deadline, "UDP receive deadline"), cancellation) }
fn terrane_platform_dns_lookup(host: String, port: terrane_int_support::Int, deadline: terrane_int_support::Int, cancellation: &TerranePlatformCapability) -> TerranePlatformResult { terrane_platform_support::dns_lookup(&host, terrane_platform_i128!(port, "DNS port"), terrane_platform_i128!(deadline, "DNS deadline"), cancellation) }
fn terrane_platform_close(capability: &TerranePlatformCapability) -> TerranePlatformResult { terrane_platform_support::close(capability) }
